//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class odzywki
{
    public odzywki()
    {
        this.zamowienia = new HashSet<zamowienia>();
    }

    public long Id { get; set; }
    public string Nazwa { get; set; }
    public string Opis { get; set; }
    public Nullable<double> Cena { get; set; }
    public Nullable<int> Typ { get; set; }

    public virtual ICollection<zamowienia> zamowienia { get; set; }
}

public partial class urzadzenia
{
    public long id { get; set; }
    public string Nazwa { get; set; }
    public string Opis { get; set; }
    public Nullable<double> Cena { get; set; }
}

public partial class uzytkownicy
{
    public uzytkownicy()
    {
        this.zamowienia = new HashSet<zamowienia>();
    }

    public long id { get; set; }
    public Nullable<double> Cena { get; set; }
    public string Login { get; set; }
    public string Haslo { get; set; }

    public virtual ICollection<zamowienia> zamowienia { get; set; }
}

public partial class zamowienia
{
    public long id { get; set; }
    public long idUzytkownika { get; set; }
    public long idOdzywki { get; set; }

    public virtual odzywki odzywki { get; set; }
    public virtual uzytkownicy uzytkownicy { get; set; }
}
